### ISSUE TITLE
Doc Comments

### ISSUE THREAD

**Issue by wyatt-herkamp** [udoprog/genco#25] opened 2022-06-21 20:54 UTC
So this is my code
```rust
    pub fn generate_variant_def(&self) -> Tokens<Rust> {
        let name = &self.name.to_case(Case::UpperCamel);
        let requirement = &self.requirement;
        let switch_variant_type = self.switch_variant_type.generate_variant_type();
        quote! {
            ///This switch variant requires a value #requirement in the compare_to field
            #<line>
            #name #switch_variant_type,
        }
    }
```
It generates 
```rust
# [ doc = "This switch variant requires a value #requirement in the compare_to field" ]

 MyVariant {

 test: i32 ,

 } ,
``` 

Requirement is equal to "12"

**Comment by udoprog** [comment] 2022-06-22 07:27
I'm not following. Could you try and elaborate on what the issue is?

**Comment by udoprog** [comment] 2022-06-22 10:18
Gotcha, so interpolation does indeed not work inside of rust-style comments because they are passed into the macros as literal strings (as you can see in how they are expanded).

The way you have to work around this is by formatting the comment yourself:

```rust
quote! {
    #(format!("/// This switch variant requires a value {requirement} in the compare_to field"))
    #<line>
    #name #switch_variant_type,
}
```

I've also opened #26 which will allow you to use `format_args!` directly once merged, all though it would fundamentally accomplish the same thing.

**Closed as completed** 2022-06-22 12:29 UTC
Labels: question
